language: node_js
node_js:
- '8.10'
before_install:
- npm i -g npm@6.2
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: j2GJ6t2tgzMEga90f6T0JD3ALHxMkeejgScIkIyTsrKsqfua5nxZoJTRJ8sPfFBKPDcp52vHW7o0UjaqCaYLr0NqWXUliWfd4+kfUHqYNW7BvNoGzfRalEXJwI5pHzlWoDeVAVE/RhxSCNe6sMvVUcm74/HG7AkBA3W+uQi7vcqYUspwpuqeCMgWPD3qk01+EVy3L59km+aAn21CGu/sJbWAz/hstYf87/LmwRrWuZJ4WaGqqUE7Yu9EEkrjYA9BE0w1zp7cAG6KropqTX77/KcEVdtmCVJDGoqAVDAW+k3NbNmwumuhkq4CI4B0Op/GbyZdpL7Ln7VSRvncOjkWl/ALcE9VIkvkRE5yjRxxXSUQL0K9zA2OovYuLKBU8MOmgu8gTPMRT8v23zlX55gdRDvOEkpD06GPIoQyuHebvJnhdNukWZTVFpNHPceTtwks1Xs/x1Fz3KQmEcMJK5APM/hKLEkSaClT+q9xsY+U8pXiRtVqo5ZKajbgCn73XYxvqX+jBDmbN4c+mvY1/8jKwn/1zj/7UgTKSZwA+4kA8f6btcBn/KobtdkRU9M9XL0SE9EAXrOMx3omALRA25VFKGFmH3lGTeXto1+zwDPCMeBOD5yixEM6K0q9q08lG+G+m3Gf87uLbkJJo66PgFvix8DB1Smx1axmWGr5eUyO6f0=
  app: mudboys
  on:
    tags: false